      let serviceUrl = 'http://192.168.1.150:8080'; //宇廷
// let serviceUrl = 'http://192.168.1.145:8085'; //秋生
// let serviceUrl = 'http://192.168.1.125:8080'; //发哥
//let serviceUrl = 'http://localhost';
const tool = require('../js/tool.js').tool;

const ajaxUser = {
  //获取secction
  getSessionKey(data,success){
    tool.ajax({
      url:serviceUrl+'/miniLogin/getSessionKey',
      data,
      loading:false,
      type:'GET',
      success
    })
  },
  //wx登录
  wxLogin(data,success){
    tool.ajax({
      url:serviceUrl+'/miniLogin/wxLogin',
      data,
      success
    })
  },
  // 发送短信验证码接口
  wxSendSMS(data,success){
    tool.ajax({
      url:serviceUrl+'/miniLogin/wxSendSMS',
      data,
      success,
      type:'GET'
    })
  },
  //手机号码登录
  telephoenLogin(data,success){
    tool.ajax({
      url:serviceUrl+'/miniLogin/telephoenLogin',
      data,
      success
    })
  },
  //手机号码注册
  telephoenRegister(data,success){
    tool.ajax({
      url:serviceUrl+'/miniLogin/telephoenRegister',
      data,
      success
    })
  },
  //获取个人金币记录（账户余额、总计收益、昨日收益）
  getPesonalGlodLogs(data,success){
    tool.ajax({
      url:serviceUrl+'/personalRecord/getPesonalGoldLogs',
      data,
      type:'GET',
      success
    })
  },
  //主动投递获取金币记录
  getDeliveryGoldLogs(data,success){
    tool.ajax({
      url:serviceUrl+'/personalRecord/getDeliveryGoldLogs',
      data,
      type:'POST',
      success
    })
  },
  //获取被企业下载获得金币记录
  getDownloadGoldLogs(data,success){
    tool.ajax({
      url:serviceUrl+'/personalRecord/getDownloadGoldLogs',
      data,
      type:'POST',
      success
    })
  }, //获取被企业下载获得金币记录
  baiduCity(data,success){
    tool.ajax({
      url:'https://api.map.baidu.com/geocoder/v2/',
      data,
      type:'GET',
      success
    })
  },
  //最近7天受益
  incomeStatistics(data,success){
    tool.ajax({
      url:serviceUrl+'/personalRecord/incomeStatistics',
      data,
      type:'POST',
      success
    })
  },
  //提现
  transferPayment(data,success){
    tool.ajax({
      url:serviceUrl+'/miniLogin/paymentApply',
      data,
      type:'GET',
      success
    })
  },
  //保存个人信息
  savePersonalInfo(data,success){
    tool.ajax({
      url:serviceUrl+'/personalSet/savePersonalInfo',
      data,
      type:'POST',
      success
    })
  },
  //简历完善度
  countType(success){
    tool.ajax({
      url:serviceUrl+'/resume/countType',
      type:'GET',
      success
    })
  },
  wxSignOut(data,success){
    tool.ajax({
      data,
      url:serviceUrl+'/miniLogin/wxSignOut',
      type:'GET',
      success
    })
  },
  updatetelephone(data,success){
    tool.ajax({
      data,
      url:serviceUrl+'/resume/updatetelephone',
      type:'POST',
      success
    })
  },
  updateSelfEvaluate(data,success){
    tool.ajax({
      data,
      url:serviceUrl+'/resume/updateSelfEvaluate',
      type:'POST',
      success
    })
  },
  //提现记录
  getPaymentApplyLogs(data,success){
    tool.ajax({
      data,
      url:serviceUrl+'/miniLogin/getPaymentApplyLogs',
      type:'GET',
      success
    })
  },
};

module.exports = ajaxUser;